stolostron/console-api

Makefile, README.md
Doc build steps to remove dependency on build harness
=> Doc build steps to remove dependency on build harness

Dockerfile
**Related Issue:** [closes|resolves|fixes] open-cluster-management/backlog#9536
=> update nodejs version to solve vulnerabilities

Dockerfile
Reverts open-cluster-management/console-api#275
=> Revert "update nodejs version to solve vulnerabilities"

src/v2/schema/application-helper-util.js
**Related Issue:** https://github.com/open-cluster-management/backlog/issues/9255
Tag ansible tasks created as hook
=> tag ansible hook tasks

README.md, src/v2/schema/application-helper-util.js
=> fix typo in readme

Dockerfile.prow
**Related Issue:** [closes|resolves|fixes] https://github.com/open-cluster-management/backlog/issues/10289
=> revert change to use the same as dockerfile

Dockerfile.prow
=> Add ls commands

README.md
Ray has put some fix for the publish. This no-op change will trigger a new build
=> non-op change

src/v2/schema/applicationHelper.js
https://github.com/open-cluster-management/backlog/issues/9288
=> Add deployable in member ID for Argo apps

src/v2/models/application.js, src/v2/schema/applicationHelper.js, src/v2/schema/applicationHelper.test.js, src/v2/schema/topology.js
**Related Issue:** https://github.com/open-cluster-management/backlog/issues/10124
- Implement support for apiVersion and cluster filter
- Use ManagedClusterView to get Argo app metadata from remote cluster
=> Display remote Argo app in topology

package-lock.json, package.json, src/v2/index.js
As per https://coreos.slack.com/archives/CUPTCTQR2/p1616072673002500
=> Use security-middleware from npmjs.com

README.md
=> no op change

OWNERS
**Related Issue:** [closes|resolves|fixes] https://github.com/open-cluster-management/backlog/issues/11336
=> remove cicd members

src/v2/schema/application-helper-util.js
Signed-off-by: Valentina Birsan <vbirsan@redhat.com>
**Related Issue:** https://github.com/open-cluster-management/backlog/issues/9142
https://github.com/open-cluster-management/backlog/issues/9305
Remove space from nodes id, cluster list
=> remove space from cluster name

src/v2/models/application.js, src/v2/schema/application.js, src/v2/schema/query.js
Signed-off-by: sahare <sahare@redhat.com>
https://github.com/open-cluster-management/backlog/issues/11263
=> Adding an API to get URL of a Route resource

src/v2/models/application.js, src/v2/schema/application.js, src/v2/schema/query.js
=> Change query

src/v2/mocks/AppList.js, src/v2/mocks/kube-http.js, src/v2/models/application.js, src/v2/schema/__snapshots__/application.test.js.snap, src/v2/schema/application.js, src/v2/schema/application.test.js, src/v2/schema/query.js
**Related Issue:** open-cluster-management/backlog#11292
Adds a basic query that returns OCM applications and Argo applications.
=> Fallback application query

src/v2/models/application.js, src/v2/schema/topology.js
**Related Issue:** https://github.com/open-cluster-management/backlog/issues/12005
- Add check if cluster is offline when the app is not found
=> Check if cluster is offline when the app is not found

src/v2/models/application.js
Signed-off-by: chenz4027 <magchen@redhat.com>
**Related Issue:** [closes|resolves|fixes] https://github.com/open-cluster-management/backlog/issues/12196
=> add labels copiedFrom

src/v2/models/application.js
Signed-off-by: chenz4027 <magchen@redhat.com>
**Related Issue:** [closes|resolves|fixes]  https://github.com/open-cluster-management/backlog/issues/12608
=> change ans label

Dockerfile.prow, src/v2/schema/applicationHelper.js
Signed-off-by: Valentina Birsan <vbirsan@redhat.com>
**Related Issue:** https://github.com/open-cluster-management/backlog/issues/12510
Don't try to update resource name for object store resources
=> don't try to remove chart name for obj store resources

Dockerfile.prow
Signed-off-by: chenz4027 <magchen@redhat.com>
**Related Issue:** [closes|resolves|fixes] open-cluster-management/backlog#11308
=> remove amd64

src/v2/models/application.js, src/v2/schema/application.js, src/v2/schema/query.js
**Related Issue:** [closes|resolves|fixes] https://github.com/open-cluster-management/backlog/issues/12797
=> Query to fetch managedCluster

Dockerfile.prow
Signed-off-by: Kevin Cormier <kcormier@redhat.com>
**Related Issue:** Removes dev dependencies in Prow build
=> Remove dev dependencies

Dockerfile.prow
Signed-off-by: Kevin Cormier <kcormier@redhat.com>
**Related Issue:** https://github.com/open-cluster-management/backlog/issues/13008
Remove unneeded git installation
=> Remove git installation

src/v2/models/application.js
Signed-off-by: sahare <sahare@redhat.com>
**Related Issue:** [closes|resolves|fixes] https://github.com/open-cluster-management/backlog/issues/12910
=> Update conditions to find argocd server route

SECURITY.md
Signed-off-by: chenz4027 magchen@redhat.com
**Related Issue:** [closes|resolves|fixes] https://github.com/open-cluster-management/backlog/issues/14430
=> no-op change

Dockerfile.prow, SECURITY.md
**Related Issue:** [closes|resolves|fixes] https://github.com/open-cluster-management/backlog/issues/14430
=> Fix security scan

Dockerfile.prow
Signed-off-by: Feng Xiang <fxiang@redhat.com>
**Related Issue:** https://github.com/open-cluster-management/backlog/issues/14430
- Update node image version to the latest
=> Update node image

src/v2/models/application.js, src/v2/models/placementrule.js, src/v2/schema/application.js, src/v2/schema/placementrule.js, src/v2/schema/query.js
**Related Issue:** [closes|resolves|fixes] https://github.com/open-cluster-management/backlog/issues/14305
=> Add create wizard queries

src/v2/index.js, src/v2/lib/auth-middleware.js
Signed-off-by: Kevin Cormier <kcormier@redhat.com>
=> Fix GraphQL Playground for local development

src/v2/models/application.js, src/v2/schema/application.js, src/v2/schema/query.js
**Related Issue:** [closes|resolves|fixes] https://github.com/open-cluster-management/backlog/issues/14305
=> Change getapplications for edit argo

src/v2/schema/applicationHelper.js
Signed-off-by: Feng Xiang <fxiang@redhat.com>
**Related Issue:** https://github.com/open-cluster-management/backlog/issues/14416
- Don't add HelmRelease to topo
- Also porting a 2.3 fix to 2.4 https://github.com/open-cluster-management/backlog/issues/15765
=> Don't add HelmRelease to topo

package-lock.json, package.json
Signed-off-by: Feng Xiang <fxiang@redhat.com>
**Related Issue:** https://github.com/fxiang1/console-api/pull/new/feng-15868
- Update apollo-server-express to 2.19.1
=> Update apollo-server-express to fix CVE

src/v2/models/application.js, src/v2/schema/applicationHelper.js
Signed-off-by: Maggie Chen <magchen@redhat.com>
**Related Issue:** [closes|resolves|fixes] https://github.com/open-cluster-management/backlog/issues/15198
=> Create placement node

src/v2/models/application.js
Signed-off-by: Maggie Chen <magchen@redhat.com>
Thanks @jeswanke for catching it
=> Return applicationset

src/v2/mocks/AppList.js, src/v2/mocks/kube-http.js, src/v2/models/application.js
Signed-off-by: Maggie Chen <magchen@redhat.com>
https://coreos.slack.com/archives/CUEMQ631C/p1632497731101500
=> Update gitopsclusters apiversion

package-lock.json, package.json
https://github.com/open-cluster-management/backlog/issues/18100
=> Update to json-schema 0.40.0

package-lock.json, package.json
https://github.com/open-cluster-management/backlog/issues/18100
=> [2.3] Update to json-schema 0.40.0

package-lock.json, package.json
https://github.com/open-cluster-management/backlog/issues/18100
=> [2.4] Update json-schema

.github/pull_request_template.md, Makefile, README.md, package-lock.json, package.json
https://github.com/stolostron/backlog/issues/18716
=> Switch to GH org stolostron

package-lock.json, package.json
https://github.com/stolostron/backlog/issues/16434
=> [release-2.2] Update object-path

.github/pull_request_template.md, CONTRIBUTING.md, Dockerfile.prow, Makefile, README.md, package-lock.json, package.json, src/v2/index.js
=> [release-2.3] Update to stolostron

CONTRIBUTING.md, Dockerfile.prow, Makefile, README.md, package-lock.json, package.json, src/v2/index.js
=> [release-2.4] Update to stolostron

CONTRIBUTING.md, Dockerfile.prow, Makefile, README.md, package-lock.json, package.json, src/v2/index.js
=> Update to stolostron

package-lock.json, package.json, src/v2/index.js
=> [release-2.2] More stolostron updates
